global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'datalake'
    metrics_path: /api/monitor/metrics
    scheme: http
    static_configs:
      - targets: ['datalake:52773']
    basic_auth:
      username: '_system'
      password: 'SYS'      


  - job_name: 'bankingtrnsrv'
    metrics_path: /api/monitor/metrics
    scheme: http
    static_configs:
      - targets: ['bankingtrnsrv:52773']
    basic_auth:
      username: '_system'
      password: 'SYS' 


  - job_name: 'bankingcore'
    metrics_path: /api/monitor/metrics
    scheme: http
    static_configs:
      - targets: ['bankingcore:52773']
    basic_auth:
      username: '_system'
      password: 'SYS'             