global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'iris'
    metrics_path: /api/monitor/metrics
    scheme: http
    static_configs:
      - targets: ['datalake:52773']
    basic_auth:
      username: '_system'
      password: 'SYS'